// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.6
// source: jobQueue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RunEverySec  int32  `protobuf:"varint,2,opt,name=run_every_sec,json=runEverySec,proto3" json:"run_every_sec,omitempty"`
	Seed         *int32 `protobuf:"varint,3,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	DequeueCount *int32 `protobuf:"varint,4,opt,name=dequeue_count,json=dequeueCount,proto3,oneof" json:"dequeue_count,omitempty"`
}

func (x *JobQueue) Reset() {
	*x = JobQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobQueue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobQueue) ProtoMessage() {}

func (x *JobQueue) ProtoReflect() protoreflect.Message {
	mi := &file_jobQueue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobQueue.ProtoReflect.Descriptor instead.
func (*JobQueue) Descriptor() ([]byte, []int) {
	return file_jobQueue_proto_rawDescGZIP(), []int{0}
}

func (x *JobQueue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobQueue) GetRunEverySec() int32 {
	if x != nil {
		return x.RunEverySec
	}
	return 5
}

func (x *JobQueue) GetSeed() int32 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return -1
}

func (x *JobQueue) GetDequeueCount() int32 {
	if x != nil && x.DequeueCount != nil {
		return *x.DequeueCount
	}
	return 3
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Script   string `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Parma    string `protobuf:"bytes,3,opt,name=parma,proto3" json:"parma,omitempty"`
	Priority *int32 `protobuf:"varint,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobQueue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_jobQueue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_jobQueue_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *Job) GetParma() string {
	if x != nil {
		return x.Parma
	}
	return ""
}

func (x *Job) GetPriority() int32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

var File_jobQueue_proto protoreflect.FileDescriptor

var file_jobQueue_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6a, 0x6f, 0x62, 0x51, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x75, 0x6e, 0x5f, 0x65, 0x76, 0x65,
	0x72, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x75,
	0x6e, 0x45, 0x76, 0x65, 0x72, 0x79, 0x53, 0x65, 0x63, 0x12, 0x17, 0x0a, 0x04, 0x73, 0x65, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x28, 0x0a, 0x0d, 0x64, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x0c, 0x64, 0x65, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x73, 0x65, 0x65, 0x64, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x64, 0x65, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x71, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x6d, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x6d, 0x61, 0x12, 0x1f, 0x0a, 0x08,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x72, 0x72, 0x79, 0x6b, 0x68,
	0x68, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jobQueue_proto_rawDescOnce sync.Once
	file_jobQueue_proto_rawDescData = file_jobQueue_proto_rawDesc
)

func file_jobQueue_proto_rawDescGZIP() []byte {
	file_jobQueue_proto_rawDescOnce.Do(func() {
		file_jobQueue_proto_rawDescData = protoimpl.X.CompressGZIP(file_jobQueue_proto_rawDescData)
	})
	return file_jobQueue_proto_rawDescData
}

var file_jobQueue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jobQueue_proto_goTypes = []interface{}{
	(*JobQueue)(nil), // 0: pb.JobQueue
	(*Job)(nil),      // 1: pb.Job
}
var file_jobQueue_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jobQueue_proto_init() }
func file_jobQueue_proto_init() {
	if File_jobQueue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jobQueue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobQueue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_jobQueue_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_jobQueue_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jobQueue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobQueue_proto_goTypes,
		DependencyIndexes: file_jobQueue_proto_depIdxs,
		MessageInfos:      file_jobQueue_proto_msgTypes,
	}.Build()
	File_jobQueue_proto = out.File
	file_jobQueue_proto_rawDesc = nil
	file_jobQueue_proto_goTypes = nil
	file_jobQueue_proto_depIdxs = nil
}
